- README.md
- package.json
- public/index.html
- public/views/template.html
Added a template page for the views, created routes folder, and added a template.js
> Ynikz branch

- public/index.html
- public/views/404.html
- scss/partials/_index.scss
- scss/partials/_nav.scss
- scss/styles.scss
- src/components/Footer.js
- src/components/Header.js
- src/components/ImgComp.js
- src/components/index.js
- src/containers/App.js
- src/containers/Home.js
- src/containers/Template.js
Started figuring out the css, created a Footer & Header component for the Templates.
> Add template html files

- server.js
- test.js
Added border-radius style into database
> test data for Mongodb

- scss/partials/_nav.scss
- scss/styles.scss
- src/components/EditComp.js
- src/components/Footer.js
- src/components/Header.js
- src/components/index.js
- src/containers/Template.js
Adding styles to the object for the Header & Footer of the template. Created a Edit Bar for the template.
> Add components files

- src/actions/divComp.js
- src/actions/index.js
- src/app.js
- src/components/DivComp.js
- src/containers/App.js
- src/containers/Template.js
- src/reducers/divComp.js
- src/reducers/index.js
State gets passed through from the "Template" container to the "DivComp." Action currently does nothing.
> Redux added for DivComp

- package.json
- server.js
- test.js
> Styles mongo

- src/actions/divComp.js
- src/actions/index.js
- src/app.js
- src/components/DivComp.js
- src/components/index.js
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/containers/index.js
- src/reducers/divComp.js
Edit bar will be more static, and we are going to run redux on it along with the Template container.
> Moved Edit bar to Containers

- src/containers/Edit.js
Used other method Christie had to get it off the constructor.
> Moved change methods outside of constructor.

- src/actions/divComp.js
- src/actions/index.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/divComp.js
- Div font changes when the menu is changed.
- Added another function into the div component reducer.
- Added an action to dispatch the font change.
> Added change-font functionality.

- src/components/DivComp.js
- src/containers/Edit.js
Able to console log save button to grab div style. Still needs to save to database.
> Created a save button to get style from div

- public/index.html
- server.js
- src/reducers/divComp.js
- test.js
Added jquery to index.html and render some data from Mongo database
> Able to render data from Mongo database

- public/index.html
- server.js
- src/containers/Edit.js
Route for POST request. Console logged req.body.
> set up body parser

- src/actions/divComp.js
- src/components/DivComp.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/divComp.js
Takes in an AJAX query and renders the style object.
> Can take in AJAX Query

- server.js
- src/containers/Edit.js
POST method on server for backgroundColor in MongoDB
> changed properties saved into MongoDB - backgroundColor

- .gitignore
- package.json
- server.js
-Added body-parser to package.json
-Worked on Issue #24: Set up config.json for mongo connection
> Set up configuration of Mongo database

- models/Theme.js
- models/index.js
- server.js
-Set up Theme model in reference to Issue #25
> Mongo database models

- scss/partials/_nav.scss
- scss/styles.scss
- src/components/Header.js
- src/containers/Edit.js
Removed the button that I created, and ending up adding a className to the button that Sheena created. Fixing the CSS for the template.
> Fixing the CSS for the template

- src/actions/divComp.js
- src/components/ColorMenu.js
- src/components/FontMenu.js
- src/containers/Template.js
- src/reducers/divComp.js
- test.js
Added code to change only the second div that renders based off of the "elementId" value.
Caveats:
- The "elementId" value is currently hardcoded.
- There will be refactoring where there is a single action & reducer to take in all styles and validate if a particular style changed.
> Edit Menu Changes One Div

- src/containers/Edit.js
Able to save styles from selected elements through DOM. WIP using React/Redux.
> Attributes to mongo

- src/actions/divComp.js
- src/components/ColorMenu.js
- src/components/DivComp.js
- src/components/FontMenu.js
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/divComp.js
The Div Components can be selected by clicking it. Changing either the font or color dropdown will modify the selected div.
> Select and Change Div On Click

- src/components/DivComp.js
- src/components/ImgComp.js
- src/components/PComp.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
- test.js
Img now works. Forgot to checkout a new branch.
> Added Img Component Dynamically

- server.js
Included subtypes into schema on Mongoose
> Updated Schema

- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
Changed files within TemplateEdit.js, moved my function into this file as it is the parent file of the Template and Edit containers
> When selecting elements, styles show beneath

- src/components/ListComp.js
- src/components/ListItem.js
- src/components/index.js
- src/containers/Template.js
- Component returns an li tag.
> Added ListItem component.

- src/actions/index.js
- src/components/ColorMenu.js
- src/components/ListComp.js
- src/components/ListItem.js
- src/components/index.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/colors.js
Color menu renders and changes colors of elements.
Merging this PR will also merge PR #68
> Render color menu

- src/actions/index.js
- src/components/ColorMenu.js
- src/components/FontMenu.js
- src/components/ListComp.js
- src/components/ListItem.js
- src/components/index.js
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/colors.js
- src/reducers/fontDropdown.js
- src/reducers/index.js
Added initial state through font reducer. Renders two font families, plus the other two that are hardcoded in.
WARNING: Merging this request will also merge in PR #68 and #69
> Render font menu

- server.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
> Saving styles to Mongo

- src/actions/colors.js
- src/actions/index.js
- src/constants/actionTypes.js
- src/containers/TemplateEdit.js
- src/reducers/colors.js
- test.js
- Adding the services folders.
- Adding the color.js to get the data from the API.
- Adding the font.js to get the data from the API.
- Creating the colorPalette file to render data...
> Fixing Merge Conflicts

- src/containers/TemplateEdit.js
- src/reducers/colors.js
> passing initial state

- src/containers/Edit.js
- src/containers/TemplateEdit.js
- Able to call ColourLovers api and render sample colors in reference to issue #91 and #92
> Use color api

- src/containers/Edit.js
- To export styles from components from mock string
- Added button to Edit.js container
- Function is not attached to any component
- Function is not added to Redux
> Created base function exportAsCSSFile() 

- package.json
- public/index.html
- server.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
Now running on Localhost:3000 no live reload with npm run dev.
> Changed webpack

- server.js
- src/containers/Edit.js
Fixed the Ajax request and server to POST template and save to Mongo.
> Save template

- src/components/ImgComp.js
- src/components/ListComp.js
- src/components/ListItem.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
Shows a blue outline around the selected element.
Resolves #79
> Highlight selected component

- src/containers/TemplateEdit.js
- Used colr.org api to retrieve random colors for dropdown menu in reference to issues #91 and #92
- Some HEX values are empty and break the function. Used conditional statements to set color as #FFF for empty HEX values.
- Removed reference to ColourLovers.com API
> Change Color API source

- server.js
Included background color, font family, font color, and display as a starting point for ra list of styles we want the user to be able to modify.
> Modified doc to include set of styles for user to be able to modify

- src/containers/Edit.js
saveStyle function was being called multiple times on render. Fixed to be called once.
> Created a save function in the constructor. 

- public/index.html
- src/components/ColorMenu.js
- src/components/FontMenu.js
- src/containers/TemplateEdit.js
- src/reducers/fonts.js
- Able to render Google Fonts in reference to issue #91 
- Font source files cannot be added inline so they are loaded on index.html to be moved later
- Added default value option for both font/color dropdown menus
> Use font api

- public/views/404.html
- scss/partials/_cssview.scss
- scss/styles.scss
- src/containers/CssView.js
- src/containers/TemplateEdit.js
- src/containers/index.js
Creating a Css View for the user to either copy/view the CSS.
> Adding the CssView for the user.

- src/components/DivComp.js
- src/components/ImgComp.js
- src/components/ListComp.js
- src/components/ListItem.js
- src/components/PComp.js
- src/containers/Template.js
Components now have `elementId` appended to `className` to target specific component through class.
> Appended elementId to className

- package.json
- src/containers/Edit.js
- If no filename is provided, file is automatically named with current date (Must fix date)
- File is saved as SCSS
- File is formatted for SCSS format (Must insert ";" at end of elementStyle string)
> Client can save inline styles from all components

- src/actions/elementsActions.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
Adds and passes the mongo id to the `Edit.js` container.
> Pass mongo objectid

- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
ObjectId was being removed on state when selecting a new element. Fixed this issue.
> ObjectId Does Not Delete From State

- src/components/Template/ListComp.js
- List Component was not importing the List Item Component.
- Fixed path for the import.
> Fixed import error on ListComp.

- src/containers/Edit.js
- src/containers/TemplateEdit.js
Going to create a new branch to figure out how to make the toggle hide work for two components on the Edit container....
> Still working on the toggle for the Edit Menu.

- scss/partials/_index.scss
- scss/partials/_nav.scss
- scss/styles.scss
- src/containers/Home.js
- Fixed white space by footer and overall styling for home page
> Styling for Home Page

- server.js
- src/containers/Edit.js
Able to update the template styles in mongo and get doc by id. Routes /update/new/:id added.
> PUT and GET :id

- scss/partials/_index.scss
- scss/styles.scss
- src/containers/Edit.js
- src/containers/Template.js
-Edit styling for template page
> Css styling for app

- package.json
- server.js
- src/containers/Edit.js
npm i --save shortid
Updated the routes for POST and PUT. Shorter Ids are created from the ObjectId.
> Shorter Ids for ObjectId

- src/actions/elementsActions.js
- src/components/Edit/FontMenu.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
- Added font colors to editable list of properties
- Using a sample list of colors, will pull from API later
> Add Font Colors

- src/actions/elementsActions.js
- src/components/Edit/FontMenu.js
- src/components/Template/Header.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
- Able to change font size of selected element
- Able to change font color of selected element
- Able to choose between rem and px for font size
> Components for css properties

- src/components/Template/DivComp.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
- test.js
Also fixed the `selectElement` function. However, unable to change the second child at this moment.
> Div Components render up to second child

- server.js
- src/components/Template/DivComp.js
- src/components/Template/Footer.js
- src/components/Template/HComp.js
- src/components/Template/Header.js
- src/components/Template/ImgComp.js
- src/components/Template/ListComp.js
- src/components/Template/PComp.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
- test.js
Renders the example template. There are no styles, but all the class names and tiers are set to the sample template.
- The template container does not start from the body. It is a few levels down.
- The `test.js` and schema on `server.js` have changed. Elements are now an array of objects instead of an object separated by tags.
- NOTE: This will also merge pull request #134.
> Render example template

- src/actions/elementsActions.js
- src/components/Edit/ColorMenu.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
Changes colors based on relationship level, (i.e., all parents are one color, all first children are another color, all second children are a unique color, etc.).
> Change template color palette

- public/index.html
- src/components/Template/DivComp.js
- test.js
Added style script @herrolisa provided and removed the inline styles to accommodate changes.
> Added Style Script

- scss/styles.scss
- src/actions/elementsActions.js
- src/components/Edit/ColorMenu.js
- src/components/Template/Header.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
When the user clicks on the button for the Font & Div menu it moves to a 90 degree.
> Animating the toggle button for the Edit.

- src/actions/elementsActions.js
- src/components/Edit/ColorMenu.js
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
It is now an action dispatcher function rather than handled through the reducer. It also uses the `changeColor` action to dispatch instead of creating a new action to handle changing all the elements.
> Theme Color Switcher Moved

- scss/partials/_cssview.scss
- scss/styles.scss
- src/containers/App.js
- src/containers/Edit.js
- The CSS view button is now positioned next to the Edit.
- When the user clicks on the CSS button the view goes over the Edit column.
> Fixing css view

- src/components/Edit/ColorMenu.js
- src/components/Template/DivComp.js
- src/components/Template/Footer.js
- src/components/Template/Header.js
- src/components/Template/ImgComp.js
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
- test.js
`switchThemeColor` now changes the background color
- Added the parent div into the DB to access its style
- Added the `Header` and `Footer` component to the DB.
> Change Background on switchThemeColor

- server.js
- src/containers/Edit.js
Changed the data for the ajax request on Edit.js from this.props.doc to this.props.elementsReducer.doc.elements to get the elements into database.
> Fixed ajax request for save and update

- src/actions/elementsActions.js
- src/actions/fonts.js
- src/components/Edit/ColorMenu.js
- src/components/Edit/FontMenu.js
- src/containers/Edit.js
- src/reducers/colors.js
- src/reducers/elementsReducer.js
- src/reducers/fonts.js
- Selecting a font changes the entire document's font.
> Change font now changes all elements' fonts.

- public/index.html
- scss/partials/_index.scss
- scss/styles.scss
- src/containers/About.js
- src/containers/Home.js
- Worked on app overall styling
- Edited Footer
- Added About Page
> Styling For Web App

- src/containers/Edit.js
+ Zip files button added
++ HTML and CSS files are in this zip
- HTML and CSS buttons taken out
- HTML and CSS functions taken out
> Zip button works

- server.js
- src/actions/index.js
- src/actions/styles.js
- src/components/Edit/ColorMenu.js
- src/components/Edit/FontMenu.js
- src/containers/TemplateEdit.js
- src/reducers/index.js
- src/reducers/styles.js
- test.js
Added a `Styles` collection in the DB.
- `TemplateEdit` loads the `Styles` document.
- Action and reducer adds the object to state and the default selected element to state.
> Created Styles Collection

- package.json
- src/components/Edit/ColorMenu.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
Loads the `styles` document from the DB and both sets the default background colors and changes between two different palettes.
> Background colors load through DB

- package.json
- public/index.html
- scss/styles.scss
- src/components/Template/Footer.js
- src/components/Template/Header.js
- src/components/Template/ImgComp.js
- src/components/Template/PComp.js
- test.js
- Created default styles for template-1
- Add new hero image
- Created navigation menu
- Adjust font size
> Template 1 Styles

- server.js
- src/containers/Template.js
Still needs an action to render the styles from usertemplates collection. Currently renders default template.
> Page renders from database with the hash

- server.js
- src/containers/Edit.js
Fixed route on editSave function. Update button now works. Also removed console.logs.
> Fixed route on Edit.js

- src/containers/About.js
- src/containers/App.js
- src/containers/Footer.js
- src/containers/Home.js
- src/containers/index.js
- Created reusable footer component
> App Styling - Footer

- public/index.html
- Separate background shorthand property into their individual background properties
> Separate background property for Template-1 Hero Container

- server.js
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
Saved user templates now render.
> Fix saved template rendering

- src/app.js
- src/components/Edit/FontMenu.js
- src/containers/App.js
- src/containers/Edit.js
- src/containers/Resource.js
- src/containers/index.js
> Resource route

- server.js
- src/containers/Edit.js
> Created function for the drop down of saved templates

- public/index.html
- src/components/Template/ImgComp.js
- test.js
- Edit styles to create a more modern look
- Add more content to the template
- Change dummy text
> Edit Template 1 For A Modern Look

- src/containers/Edit.js
Click on the drop down to populate.
> Dropdown menu added for saved templates

- src/containers/Edit.js
- src/containers/TemplateEdit.js
- Adding the params.hash to the TemplateEdit.
- Removing the showUpdate function in the Edit.
- Adding this.props.updateButtonShow to the saveFilePopup function.
- Fixing the conditional statement to show the Update Component with the this.props.hash.
> Fixing Update Button

- public/index.html
- scss/styles.scss
- src/containers/About.js
- Edit About Page
- Edit Template Container
> Styling for the App

- src/components/Edit/FontMenu.js
- src/components/Template/DivComp.js
- src/components/Template/ImgComp.js
- src/components/Template/PComp.js
- src/components/index.js
- test.js
User can chose either `h1`, `h2`, or `h3` and change its respective style.
User can also chose the elements in the image component and change those styles.
> Able to Change Specific H-Tag Styles

- README.md
- scss/styles.scss
Centered image in README. Added a Z-index to the dropdown menu so that the arrows from the Edit sidebar do now appear in front of the dropdown menu.
> Edit Readme and SCSS

- public/index.html
- scss/partials/_index.scss
- scss/partials/_nav.scss
- scss/styles.scss
- src/containers/Edit.js
- src/containers/Template.js
- src/containers/TemplateEdit.js
> Minor changes to SCSS files

- server.js
- Was not updating when there were multiple templates. Query selector fixed to solve this.
> Properly updates.

- scss/styles.scss
- src/containers/About.js
- Set up CSS sprites for the photos
- Will add photos later
> CSS Sprites for About Page

- scss/styles.scss
- src/actions/menuShow.js
- src/components/Edit/FontMenu.js
- src/containers/Edit.js
- src/reducers/menuShow.js
- Convert upload image feature into a hide/show menu option
- Add icons next to menu options
> Changes to Template Style Editor

- scss/partials/_content-page.scss
- scss/styles.scss
- src/containers/About.js
- src/containers/Edit.js
- src/containers/NotFound.js
- src/containers/Resource.js
- Cleaned CSS code using DRY method
- Working on saved templates styling
> Cleaning up CSS code

- src/containers/Edit.js
Dropdown lists dates instead of hash
> Edit Dropdown

- src/containers/Edit.js
- Now able to change image with a URL.
> Added URL field for images.

- server.js
- src/actions/elementsActions.js
- src/containers/Edit.js
- src/containers/TemplateEdit.js
- src/reducers/elementsReducer.js
Added a dropdown with the names of the templates instead of the hashes.
> Able to Chose Saved Templates By Name

- src/containers/Edit.js
Added tutorial in the readme txt.
> Updated readme

- scss/partials/_content-page.scss
- scss/styles.scss
- Adjust media queries for About page photos. Should fix problem referenced in Issue #238
> About Page

- src/containers/Edit.js
Updated README. Default value for the name of template styles is now Hue with timestamp. Needs styling.
> Edited Input Default Value

- src/containers/Edit.js
- test.js
- Adding more palette's to the test.js file.
- Adding the fonts from the index.js as well.. so the user has more fonts.
> Adding more palettes.

- src/containers/Edit.js
Set a default for the template scrollbar.
> Edit Choose Template Button

- src/components/Template/DivComp.js
- src/components/Template/ImgComp.js
- src/components/Template/PComp.js
- src/containers/Template.js
Buttons colors take index 0 from the selected color palette.
> Buttons Change on Palette Swap

- gulpfile.js
- package.json
- scss/partials/_content-page.scss
- scss/styles.scss
- src/containers/About.js
- Install gulp-autoprefixer
- Update About Page
> About Page/Styling

- test.js
Making small changes to the palette.
> Modifying Palette

- src/containers/Tutorial.js
added high definition link for tutorial video
> High Def Vid

- src/containers/Tutorial.js
Keeping the content consistent with the layout...
> Making small minor changes.

- scss/partials/_popover.scss
- scss/styles.scss
- src/containers/Edit.js
> Style editor for templates

- src/containers/About.js
> Edited about info

- src/containers/About.js
- It was not wrapping and forced extra pixels in the div.
- Also put my description in lower case.
> Added a space in Sheena's description.

- README.md
Added www.stylesforhue.com to readme.
> Added website link to readme

- public/index.html
- scss/partials/_colors.scss
- scss/partials/_content-page.scss
- scss/partials/_footer.scss
- scss/partials/_index.scss
- scss/partials/_nav.scss
- scss/partials/_popover.scss
- scss/styles.scss
- src/containers/About.js
- src/containers/Resource.js
- src/containers/Tutorial.js
- Update styling on About, Resources, Tutorial
- Cleaned up CSS to reduce repetitive code
> Fix Styling In Preparation For RWD
